# Generated by Django 5.2.7 on 2025-10-29 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('NATURAL', 'Persona natural'), ('JURIDICA', 'Persona jurídica')], max_length=20)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('NIT', 'NIT'), ('CE', 'Cédula de extranjería'), ('PAS', 'Pasaporte')], max_length=10)),
                ('numero_documento', models.CharField(max_length=30, unique=True)),
                ('digito_verificacion', models.CharField(blank=True, max_length=2)),
                ('pais', models.CharField(max_length=80)),
                ('departamento', models.CharField(max_length=80)),
                ('municipio', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=200)),
                ('razon_social', models.CharField(blank=True, max_length=150)),
                ('nombre_comercial', models.CharField(blank=True, max_length=150)),
                ('tipo_empresa', models.CharField(blank=True, max_length=120)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('numero_celular', models.CharField(max_length=20)),
                ('quien_diligencia', models.CharField(blank=True, max_length=120)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_limite', models.DateField()),
                ('completada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='personas.persona')),
            ],
            options={
                'ordering': ['completada', 'fecha_limite'],
            },
        ),
    ]
