# Generated by Django 5.2.7 on 2025-10-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='tipo_empresa',
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_empresa_cacaotera',
            field=models.CharField(blank=True, choices=[('COM', 'Comercializador'), ('TRA', 'Transformador'), ('EXP', 'Exportador')], max_length=3),
        ),
        migrations.AlterField(
            model_name='persona',
            name='departamento',
            field=models.CharField(choices=[('ATL', 'Atlántico'), ('BOL', 'Bolívar'), ('CES', 'Cesar')], max_length=3),
        ),
        migrations.AlterField(
            model_name='persona',
            name='municipio',
            field=models.CharField(choices=[('BOG', 'Bogotá D. C.'), ('MED', 'Medellín'), ('CLO', 'Cali')], max_length=3),
        ),
        migrations.AlterField(
            model_name='persona',
            name='pais',
            field=models.CharField(choices=[('CO', 'Colombia'), ('EC', 'Ecuador'), ('PE', 'Perú'), ('BO', 'Bolivia')], max_length=2),
        ),
    ]
